version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.11
    commands:
      - echo "Installing SAM CLI..."
      - pip3 install aws-sam-cli
  
  build:
    commands:
      - echo "Building backend with SAM..."
      - cd backend
      - sam build
      - echo "Deploying to production..."
      - sam deploy --config-env production --no-confirm-changeset

artifacts:
  files:
    - '**/*'
  base-directory: backend/.aws-sam/build
