AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Far Too Young Authentication API

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues: [development, staging, production]
    Description: Deployment environment
  
  DynamoDBEndpoint:
    Type: String
    Default: http://host.docker.internal:8000
    Description: Endpoint for local DynamoDB endpoint (leave empty for production)
  
  JWTSecret:
    Type: String
    Default: "dev-secret-key"
    Description: JWT signing secret
    NoEcho: true

  StripeSecretKey:
    Type: String
    Default: "sk_test_..."
    Description: Stripe secret key for payment processing
    NoEcho: true

  StripeWebhookSecret:
    Type: String
    Default: "whsec_..."
    Description: Stripe webhook endpoint secret
    NoEcho: true

Globals:
  Function:
    Runtime: nodejs18.x
    Environment:
      Variables:
        DYNAMODB_ENDPOINT: !Ref DynamoDBEndpoint
        JWT_SECRET: !Ref JWTSecret
        USERS_TABLE: !Sub "${AWS::StackName}-users-table"
        DONATIONS_TABLE: !Sub "${AWS::StackName}-donations-table"
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"

Resources:
  # Authentication Functions
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/auth/login.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-users-table"
      Events:
        LoginApi:
          Type: Api
          Properties:
            Path: /auth/login
            Method: post

  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/auth/register.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-users-table"
      Events:
        RegisterApi:
          Type: Api
          Properties:
            Path: /auth/register
            Method: post

  LogoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/auth/logout.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-users-table"
      Events:
        LogoutApi:
          Type: Api
          Properties:
            Path: /auth/logout
            Method: post

  ForgotPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/auth/forgot-password.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-users-table"
      Events:
        ForgotPasswordApi:
          Type: Api
          Properties:
            Path: /auth/forgot-password
            Method: post

  ResetPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/auth/reset-password.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-users-table"
      Events:
        ResetPasswordApi:
          Type: Api
          Properties:
            Path: /auth/reset-password
            Method: post

  UpdateProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/auth/update-profile.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-users-table"
      Events:
        UpdateProfileApi:
          Type: Api
          Properties:
            Path: /auth/update-profile
            Method: post

  ChangePasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/auth/change-password.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-users-table"
      Events:
        ChangePasswordApi:
          Type: Api
          Properties:
            Path: /auth/change-password
            Method: post

  # Donation Functions
  CreateDonationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/donations/create-donation.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-donations-table"
      Events:
        CreateDonationApi:
          Type: Api
          Properties:
            Path: /donations
            Method: post

  GetDonationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/donations/get-donations.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-donations-table"
      Events:
        GetDonationsApi:
          Type: Api
          Properties:
            Path: /donations
            Method: get

  # Stripe Payment Functions
  CreateCheckoutSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/stripe/create-checkout-session.handler
      Environment:
        Variables:
          STRIPE_SECRET_KEY: !Ref StripeSecretKey
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-donations-table"
      Events:
        CreateCheckoutSessionApi:
          Type: Api
          Properties:
            Path: /stripe/create-checkout-session
            Method: post

  StripeWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/stripe/webhook.handler
      Environment:
        Variables:
          STRIPE_SECRET_KEY: !Ref StripeSecretKey
          STRIPE_WEBHOOK_SECRET: !Ref StripeWebhookSecret
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-donations-table"
      Events:
        StripeWebhookApi:
          Type: Api
          Properties:
            Path: /stripe/webhook
            Method: post

  # DynamoDB Tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-users-table"
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  DonationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-donations-table"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiGatewayApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

