AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Far Too Young Authentication API
# Updated: 2024-12-19 - Fixed secret key case consistency

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues: [development, staging, production]
    Description: Deployment environment
  
  DynamoDBEndpoint:
    Type: String
    Default: http://host.docker.internal:8000
    Description: Endpoint for local DynamoDB endpoint (leave empty for production)
  
  SecretsManagerArn:
    Type: String
    Default: ""
    Description: ARN of the Secrets Manager secret containing application secrets
    NoEcho: true

Conditions:
  IsProduction: !Equals [!Ref Environment, production]
  IsStaging: !Equals [!Ref Environment, staging]

Globals:
  Function:
    Runtime: nodejs18.x
    Environment:
      Variables:
        DYNAMODB_ENDPOINT: !Ref DynamoDBEndpoint
        SECRETS_MANAGER_ARN: !Ref SecretsManagerArn
        USERS_TABLE: !Sub "${AWS::StackName}-users-table"
        DONATIONS_TABLE: !Sub "${AWS::StackName}-donations-table"
        SES_FROM_EMAIL: admin@fartooyoung.org
        SES_REGION: !Ref AWS::Region
        FRONTEND_URL: !If 
          - IsProduction
          - "https://www.fartooyoung.org"
          - !If
            - IsStaging
            - "https://staging.fartooyoung.org"
            - "http://localhost:5173"
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"

Resources:
  # Authentication Functions
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/auth/login.handler
      Environment:
        Variables:
          RATE_LIMIT_TABLE: !Sub "${AWS::StackName}-rate-limits"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-users-table"
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-rate-limits"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref SecretsManagerArn
      Events:
        LoginApi:
          Type: Api
          Properties:
            Path: /auth/login
            Method: post

  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/auth/register.handler
      Environment:
        Variables:
          RATE_LIMIT_TABLE: !Sub "${AWS::StackName}-rate-limits"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-users-table"
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-rate-limits"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref SecretsManagerArn
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"
      Events:
        RegisterApi:
          Type: Api
          Properties:
            Path: /auth/register
            Method: post

  LogoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/auth/logout.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-users-table"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref SecretsManagerArn
      Events:
        LogoutApi:
          Type: Api
          Properties:
            Path: /auth/logout
            Method: post

  ForgotPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/auth/forgot-password.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-users-table"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"
      Events:
        ForgotPasswordApi:
          Type: Api
          Properties:
            Path: /auth/forgot-password
            Method: post

  ResetPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/auth/reset-password.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-users-table"
      Events:
        ResetPasswordApi:
          Type: Api
          Properties:
            Path: /auth/reset-password
            Method: post

  UpdateProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/auth/update-profile.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-users-table"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref SecretsManagerArn
      Events:
        UpdateProfileApi:
          Type: Api
          Properties:
            Path: /auth/update-profile
            Method: post

  ChangePasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/auth/change-password.handler
      Timeout: 30
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-users-table"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref SecretsManagerArn
      Events:
        ChangePasswordApi:
          Type: Api
          Properties:
            Path: /auth/change-password
            Method: post

  VerifyEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/auth/verify-email.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-users-table"
      Events:
        VerifyEmailApi:
          Type: Api
          Properties:
            Path: /auth/verify-email
            Method: get

  ResendVerificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/auth/resend-verification.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-users-table"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"
      Events:
        ResendVerificationApi:
          Type: Api
          Properties:
            Path: /auth/resend-verification
            Method: post

  # Donation Functions
  CreateDonationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/donations/create-donation.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-donations-table"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref SecretsManagerArn
      Events:
        CreateDonationApi:
          Type: Api
          Properties:
            Path: /donations
            Method: post

  GetDonationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/donations/get-donations.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-donations-table"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref SecretsManagerArn
      Events:
        GetDonationsApi:
          Type: Api
          Properties:
            Path: /donations
            Method: get

  # Stripe Payment Functions
  CreateCheckoutSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/stripe/create-checkout-session.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-donations-table"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref SecretsManagerArn
      Events:
        CreateCheckoutSessionApi:
          Type: Api
          Properties:
            Path: /stripe/create-checkout-session
            Method: post

  CreatePaymentIntentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/stripe/create-payment-intent.handler
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref SecretsManagerArn
      Events:
        CreatePaymentIntentApi:
          Type: Api
          Properties:
            Path: /stripe/create-payment-intent
            Method: post

  CreatePortalSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/stripe/create-portal-session.handler
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref SecretsManagerArn
      Events:
        CreatePortalSessionApi:
          Type: Api
          Properties:
            Path: /stripe/create-portal-session
            Method: post

  ListSubscriptionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/stripe/list-subscriptions.handler
      Timeout: 30
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref SecretsManagerArn
      Events:
        ListSubscriptionsApi:
          Type: Api
          Properties:
            Path: /stripe/list-subscriptions
            Method: get

  StripeWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/stripe/webhook.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${AWS::StackName}-donations-table"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref SecretsManagerArn
      Events:
        StripeWebhookApi:
          Type: Api
          Properties:
            Path: /stripe/webhook
            Method: post

  # DynamoDB Tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-users-table"
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  DonationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-donations-table"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  RateLimitsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-rate-limits"
      AttributeDefinitions:
        - AttributeName: limitKey
          AttributeType: S
      KeySchema:
        - AttributeName: limitKey
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

Outputs:
  ApiGatewayApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

