AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Far Too Young Authentication API

# Parameters for different environments
Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues: [development, production]
    Description: Deployment environment
  
  DynamoDBEndpoint:
    Type: String
    Default: http://host.docker.internal:8000
    Description: Endpoint for local DynamoDB endpoint (leave empty for production)
  
  JWTSecret:
    Type: String
    Default: "dev-secret-key"
    Description: JWT signing secret
    NoEcho: true

Globals:
  Function:
    Environment:
      Variables:
        DYNAMODB_ENDPOINT: !Ref DynamoDBEndpoint
        JWT_SECRET: !Ref JWTSecret
        AWS_ACCESS_KEY_ID: dummy
        AWS_SECRET_ACCESS_KEY: dummy

Resources:
  # Login Function
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/auth/login.handler
      Runtime: nodejs18.x
      Events:
        LoginApi:
          Type: Api
          Properties:
            Path: /auth/login
            Method: post
            Cors:
              AllowMethods: "'POST,OPTIONS'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'*'"
        LoginOptions:
          Type: Api
          Properties:
            Path: /auth/login
            Method: options

  # Register Function  
  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/auth/register.handler
      Runtime: nodejs18.x
      Events:
        RegisterApi:
          Type: Api
          Properties:
            Path: /auth/register
            Method: post
            Cors:
              AllowMethods: "'POST,OPTIONS'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'*'"
        RegisterOptions:
          Type: Api
          Properties:
            Path: /auth/register
            Method: options

  # Forgot Password Function
  ForgotPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/auth/forgot-password.handler
      Runtime: nodejs18.x
      Events:
        ForgotPasswordApi:
          Type: Api
          Properties:
            Path: /auth/forgot-password
            Method: post
            Cors:
              AllowMethods: "'POST,OPTIONS'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'*'"
        ForgotPasswordOptions:
          Type: Api
          Properties:
            Path: /auth/forgot-password
            Method: options

  # Reset Password Function
  ResetPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/auth/reset-password.handler
      Runtime: nodejs18.x
      Events:
        ResetPasswordApi:
          Type: Api
          Properties:
            Path: /auth/reset-password
            Method: post
            Cors:
              AllowMethods: "'POST,OPTIONS'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'*'"
        ResetPasswordOptions:
          Type: Api
          Properties:
            Path: /auth/reset-password
            Method: options

  # Logout Function
  LogoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/auth/logout.handler
      Runtime: nodejs18.x
      Events:
        LogoutApi:
          Type: Api
          Properties:
            Path: /auth/logout
            Method: post
            Cors:
              AllowMethods: "'POST,OPTIONS'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'*'"
        LogoutOptions:
          Type: Api
          Properties:
            Path: /auth/logout
            Method: options

  # Create Donation Function
  CreateDonationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/donations/create-donation.handler
      Runtime: nodejs18.x
      Events:
        CreateDonationApi:
          Type: Api
          Properties:
            Path: /donations
            Method: post
            Cors:
              AllowMethods: "'POST,OPTIONS'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'*'"
        CreateDonationOptions:
          Type: Api
          Properties:
            Path: /donations
            Method: options

  # Get Donations Function
  GetDonationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda/donations/get-donations.handler
      Runtime: nodejs18.x
      Events:
        GetDonationsApi:
          Type: Api
          Properties:
            Path: /donations
            Method: get
            Cors:
              AllowMethods: "'GET,OPTIONS'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'*'"
        GetDonationsOptions:
          Type: Api
          Properties:
            Path: /donations
            Method: options

